# Generated by Django 2.2.16 on 2023-01-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='url',
            new_name='image',
        ),
    ]
